// This file was generated by Prisma, and assumes you have installed the following:
// Load .env in development; in production, env vars are injected by Docker
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
